const SEARCH_MOVIE = 'SEARCH_MOVIE';
const SET_SEARCH_FILTER = 'SET_SEARCH_FILTER';
const GET_MOVIE = 'GET_MOVIE';
const ORDER_FILTER = 'ORDER_FILTER';
const SELECT_FILM = 'SELECT_FILM';
const UNSELECT_FILM = 'UNSELECT_FILM';

export { SEARCH_MOVIE, GET_MOVIE, SET_SEARCH_FILTER, ORDER_FILTER, SELECT_FILM, UNSELECT_FILM };
